// DATATABLE ACTION TYPES

export const datatableTypes = {
  GET_REQUEST: 'DATATABLE_GET_REQUEST',
  GET_SUCCESS: 'DATATABLE_GET_SUCCESS',
  GET_FAILURE: 'DATATABLE_GET_FAILURE',
  POST_REQUEST: 'DATATABLE_POST_REQUEST',
  POST_SUCCESS: 'DATATABLE_POST_SUCCESS',
  POST_FAILURE: 'DATATABLE_POST_FAILURE'
}